# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-25 22:48
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentauthor',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=filer.fields.file.FilerFileField(null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File'),
        ),
    ]
